### ISSUE TITLE
ゲーム終了時、片方の人がゲーム終了画面に取り残される

### ISSUE THREAD

**Issue by akapochi** [kcs1959/BlockingIO-api#91]
ゲームが終わって、片方の人が「ルームを抜ける→ルームに入る」とすると、もう片方の人が終了画面で「もう一度遊ぶ」のボタンも「ルームから抜ける」のボタンも押せなくなり、何もできなくなる。

**Comment by organic-nailer** [comment]
1人になったらルーム破棄するように変更した(#76 )けど、その時は残ってた人のroom-stateも更新しないとおかしくなる
